In [ ]:
# y = X * W + b => 최종 결과 값을 만듬 

In [ ]:
# 모델과 실측 값을 비교하여 손실값을 구하고 
# 신경망을 최적화 하는 함수를 사용하여 신경망 구성을 마무리 

### RNN 모델을 이용하여 단어를 자동 완성 하는 프로그램 
- RNN의 기본 신경망은 긴단계의 데이터를 학습할 때 맨 뒤에서는 맨 앞의 정보를 잘 기억하지 못하는 특성이 있음
- 영문자 4개로 구성된 단어를  학습시켜, 글자 3개만 주어지면 나머지 한글자를 추천해 단어를 완성하는 프로그램 
- dynamic_rnn의 sequence_length옵션을 사용하면 가변 길이 단어를 학습시킬수 있다.
- 짧은 단어는 가장 긴 단어의 길이 만큼 뒷부분을 0으로 채우고, 해당언어의 길이를 계산해 sequence_length로 pass(batch_size만큼의 배열)
 => 코드가 복잡해지니까 고정단어길이_사용

- 학습시킬 데이터는 영문자로 구성된 임의의 단어를 사용할 것이고, 한 글자 한글자를 하나의 단계로 인식 
- 한 글자가 한 단계의 입력값이 되고, 총 글자수가 전체 단계가 됨 
 

In [ ]:
#입력 = 알파벳 순서에서 각 글자에 해당하는 인덱스를  원-핫인코딩으로 표현한 값
# 그러려면 알파벳 글자들을 배열에 넣고, 해당 글자의 인덱스를 구할수 있는 연관 배열(딕셔너리)만듬

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
char_arr = ['a','b','c','d','e','f','g',
            'h','i','j','k','l','m','n',
            'o','p','q','r','s','t','u',
            'v','w','x','y','z']

In [4]:
for i in enumerate(char_arr):
    for j in i:
        print(j)

0
a
1
b
2
c
3
d
4
e
5
f
6
g
7
h
8
i
9
j
10
k
11
l
12
m
13
n
14
o
15
p
16
q
17
r
18
s
19
t
20
u
21
v
22
w
23
x
24
y
25
z


In [5]:
num_dic = {}

for j,i in enumerate(char_arr):
    num_dic[i] = j
print(num_dic)

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 'w': 22, 'x': 23, 'y': 24, 'z': 25}


In [6]:
dic_len = len(num_dic)
dic_len

26

In [7]:
# 학습에 사용할 단어 
seq_data = ['word','wood','deep','dive','cold','cool','load','love','kiss','kind']

In [8]:
len(seq_data)

10

In [ ]:
# 단어들을 학습에 사용할수있는 형식으로
# 유틸리티 함수 

In [ ]:
# 1.  입력값으로, 단어의 처음 세글자의 알파벳 인덱스를 구한 배열**을 만듬
#    - input = [num_dic[n] for n in seq[:-1]]
# 2. 출력값용으로, 마지막 글자**의 알파벳 인덱스를 구함 
#    - target = num_dic[seq[-1]]
# 3. 입력값을 원-핫 **인코딩으로 변환 
#    - input_batch,append(np.eye(dic_len)[input])

In [ ]:
# input = [num_dic[n] for n in seq[:-1]]
# target = num_dic[seq[-1]]
# input_batch,append(np.eye(dic_len)[input])

In [9]:
# '''
# "deep" => 'd','e','e'
# 배열로 => [3,4,4]
# 원-핫 인코딩 최종입력값 
# '''
# 실측 값은  p의 인덱스인 15가 됨 
# 실측 값은  원- 핫 인코딩 하지 않고 15를 그대로 사용 
#=> 손실함수로 지금까지 사용하던 소프트 맥스 함수(softmax_cross_entropy_with_logits)가 
# 아닌 다른 소프트 맥스 함수(sparse_softmax_cross_entropy_with_logits)를 사용 예정 
# 이함수는 labels 값에 원 - 핫 인코딩을 사용하지않아도 자동으로 변환해서 계산해준다 

In [10]:
def make_batch(seq_data):
    input_batch  = []
    target_batch = []
    
    for seq in seq_data:
        input  = [num_dic[n] for n in seq[:-1]]
        target = num_dic[seq[-1]] 
        input_batch.append(np.eye(dic_len)[input])
        target_bacth.append(target)
        
    return input_bacth, taget_bacth

In [11]:
for seq in seq_data:
    input  = [num_dic[n] for n in seq[:-1]]

# np.eye(dic_len)[input]

print(input)

[10, 8, 13]


In [12]:
np.eye(dic_len)[input]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
for seq in seq_data:
    target = num_dic[seq[-1]] 
print(target)

3


In [14]:
input_batch  = []
target_batch = []

for seq in seq_data:
    input  = [num_dic[n] for n in seq[:-1]]
    target = num_dic[seq[-1]] 
    input_batch.append(np.eye(dic_len)[input])
    target_batch.append(target)

In [15]:
input_batch

[array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0.,

In [16]:
target_batch

[3, 3, 15, 4, 3, 11, 3, 4, 18, 3]

In [17]:
learning_rate = 0.01
n_hidden      = 128
total_epoch   = 30

In [ ]:
# 단어의 전체 중 처음 3글자를 단계적으로 학습할 것이므로 n_step = 3 
# 입력값과 출력값은 알파벳의 원- 핫 인코딩을 사용 
# 글자들의 배열 크기인 dic_len 과 같다 
# 출력 값은 원핫 인코딩을 사용해야 하므로  n_input = n_class =  dic_len 설정 

In [18]:
n_step  = 3
n_input = n_class =  dic_len

In [ ]:
# sparse_softmax_cross_entropy_with_logits 실측값인 labels 값은 인덱스의 숫자를 그대로 사용 
# 예측 모델의 출력 값은 인덱스의 원- 핫 인코딩 사용 

In [22]:
# 신경망 모델을 구성 
X = tf.placeholder(tf.float32,[None, n_step, n_input])
Y = tf.placeholder(tf.int32,[None])

W = tf.Variable(tf.random_normal([n_hidden, n_class]))
b = tf.Variable(tf.random_normal([n_class]))

In [ ]:
# Y 플레이스홀더 인덱스 숫자를 그대로 사용하기 때문에 다음처럼 값이 하나뿐인 1 차원 배열을 입력 

In [23]:
# 다음으로 두개의 RNN셀을 생성  
cell1 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
# 드랍아웃와이퍼 함수 => RNN 과적합 방지를 위한 드롭아웃 기법을 쉽게 적용
cell1 = tf.nn.rnn_cell.DropoutWrapper(cell1,output_keep_prob=0.5)
cell2 = tf.nn.rnn_cell.BasicLSTMCell(n_hidden)
# 여러 셀을 조합해 심층 신경망을 생성

Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.


In [24]:
# MultiRNNCell함수 사용 => 조합 
# 다이나믹 rnn 함수를 사용 => 심층 순화 신경망, DeepRNN 생성

multi_cell = tf.nn.rnn_cell.MultiRNNCell([cell1,cell2])
outputs, states = tf.nn.dynamic_rnn(multi_cell, X, dtype=tf.float32)


Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [25]:
outputs = tf.transpose(outputs, [1, 0, 2])
outputs = outputs[-1]
model = tf.matmul(outputs, W)+b

In [26]:
# 손실 함수 (sparse_softmax_cross_entropy_with_logits)
# 최적화 함수 (AdamOptimizer)

cost = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=model, labels=Y))
optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [ ]:
# 신경망을 학습시키는 코드
# make_batch  -> seq_data 저장한 단어들을 입력값( 첫 3글자 )과 실측값( 마지막 한글자) 분리 
# 최적화 함수를 실행하는 코드를 넣어 신경망을 학습 

sess = tf.Session()
sess.run(tf.global_variables_initializer())

input_batch,target_batch = make_batch(seq_data)

for epoch in range(total_epoch):
    _,loss = sess.run([optimizer, cost], feed_dict = {X: input_batch, Y:target_batch})
    print('Epoch:','%04d' % (epoch + 1), 'cost =','{:6f}'.format(loss))
print('최적화 완료')

In [ ]:
# 결과 값으로 예측한 단어를 정확도와 함께 출력 하도록 만들기 
prediction = tf.cast(tf.argmax(model, 1), tf.int32)
prediction_check =tf.equal(prediction, Y)
accuracy = tf.reduce_mean(tf.cast(prediction_check, tf.float32))

In [ ]:
# 인덱스를 그대로 사용 실측값(Y)는 정수 
# argmax로 변환한 값도 정수 _정확도를 구할 때 입력값을 그대로 비교 

In [ ]:
# 예측 모델 
input_batch, target_batch = make_batch(seq_data)
predict, accuracy_val = sess.run([predict,accuracy], feed_dict = {X:input_batch, Y:target_batch})

In [ ]:
# 예측한 모델 값을 가지고 각 값에 해당하는 인덱스의 알파벳을 가져와 예측단어를 출력 

predict_words =[]
for idx, val in enumerate(seq_data):
    last_char = char_arr[predict[idx]]
    predict_words.append(val[:3] + last_char)
    
print('\n===예측결과=====')
print('입력값:', [w[:3]+ ' 'for w in seq_data])
print('예측값:', predict_words)
print('정확도:', accuracy_val)
